name: "Clear Cloudflare Cache"
run-name: "Clear Cloudflare Cache"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clear-cf-cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    steps:
    - name: Clear Cloudflare Cache
      run: |
        curl -X POST -sS -H "Content-Type: application/json" "https://eoqb54s80jh905b.m.pipedream.net"
