name: "Clear Cloudflare Cache"
run-name: "Clear Cloudflare Cache"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clear-cf-cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    steps:
    - name: Clear Cloudflare Cache
    - uses: actions/setup-node@v3
    - with:
       node-version: '17.x'
    - run: node -e ""
