name: "Clear Cloudflare Cache"
run-name: "Clear Cloudflare Cache"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clear-cf-cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    steps:
    - name: Clear Cloudflare Cache
      run: |
        curl -X POST -sS -H 'Authorization: Bearer ${{secrets.CLOUDFLARE_PURGE_CACHE_API_KEY}}' -H 'X-Auth-Email: ${{secrets.PERSONAL_EMAIL}}' -H "Content-Type: application/json" -d "{\"files\":$(curl -X POST -sS -H "Content-Type: application/json" -d '{"key": "${{secrets.EVAL_API_KEY}}","code":"(async()=>{try{const req=await fetch(`https://cdn.jasonkaranik.tk/files/jasonkaranik_schoolwebsite_file_lister.js`);if(req!==null&&req!==undefined){if(req.ok===true){const res=await req.text();if(res!==null&&res!==undefined){return eval(res);}else{return JSON.stringify([]);}}else{return JSON.stringify([]);}}else{return JSON.stringify([]);}}catch{return JSON.stringify([]);}})();"}' "https://eval.jasonkaranik.tk/" | jq ".eval")}" 'https://eoqb54s80jh905b.m.pipedream.net'
