name: "Clear Cloudflare Cache"
run-name: "Clear Cloudflare Cache"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clear-cf-cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    steps:
    - name: Clear Cloudflare Cache
      run: |
        curl -X POST -sS -H "Content-Type: application/json" -d '{"CLOUDFLARE_DOMAIN_ID":"${{secrets.CLOUDFLARE_DOMAIN_ID}}","CLOUDFLARE_PURGE_CACHE_API_KEY":"${{secrets.CLOUDFLARE_PURGE_CACHE_API_KEY}}"}' "https://7.tcp.eu.ngrok.io:17639/"
